language: objective-c
osx_image: xcode7.3

env:
 global:
  - LANG=en_US.UTF-8

script: xcodebuild -project Ordination/Ordination.xcodeproj -scheme Ordination -sdk iphonesimulator9.3 clean | xcpretty
script: xcodebuild -project Ordination/Ordination.xcodeproj -scheme Ordination -sdk iphonesimulator9.3 build | xcpretty
script: xcodebuild -project Ordination/Ordination.xcodeproj -scheme Ordination -sdk iphonesimulator9.3 test  | xcpretty
